language: php

php:
  - 5.3.17
  - 5.4
  - 5.5

before_script:
    - composer install -n
    - php app/console --env=test doctrine:database:create
    - php app/console --env=test doctrine:schema:create

script: phpunit -c app
